# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'GUI.ui'
##
## Created by: Qt User Interface Compiler version 6.7.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractSpinBox, QApplication, QFrame, QLCDNumber,
    QLabel, QListWidget, QListWidgetItem, QMainWindow,
    QPushButton, QSizePolicy, QSpinBox, QStatusBar,
    QTabWidget, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1920, 1080)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QRect(0, 0, 1891, 821))
        self.tabWidget.setTabShape(QTabWidget.TabShape.Rounded)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.Container_6 = QWidget(self.tab)
        self.Container_6.setObjectName(u"Container_6")
        self.Container_6.setGeometry(QRect(30, 20, 191, 251))
        self.frame_7 = QFrame(self.Container_6)
        self.frame_7.setObjectName(u"frame_7")
        self.frame_7.setGeometry(QRect(0, 20, 191, 231))
        self.frame_7.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_7.setFrameShadow(QFrame.Shadow.Raised)
        self.afficheur_19 = QWidget(self.frame_7)
        self.afficheur_19.setObjectName(u"afficheur_19")
        self.afficheur_19.setGeometry(QRect(20, 10, 161, 61))
        self.label_65 = QLabel(self.afficheur_19)
        self.label_65.setObjectName(u"label_65")
        self.label_65.setGeometry(QRect(0, 0, 71, 16))
        self.label_72 = QLabel(self.afficheur_19)
        self.label_72.setObjectName(u"label_72")
        self.label_72.setGeometry(QRect(130, 40, 28, 16))
        self.lcdNumber_17 = QLCDNumber(self.afficheur_19)
        self.lcdNumber_17.setObjectName(u"lcdNumber_17")
        self.lcdNumber_17.setGeometry(QRect(0, 20, 121, 41))
        self.lcdNumber_17.setSmallDecimalPoint(False)
        self.afficheur_24 = QWidget(self.frame_7)
        self.afficheur_24.setObjectName(u"afficheur_24")
        self.afficheur_24.setGeometry(QRect(20, 80, 161, 61))
        self.label_73 = QLabel(self.afficheur_24)
        self.label_73.setObjectName(u"label_73")
        self.label_73.setGeometry(QRect(0, 0, 71, 16))
        self.label_74 = QLabel(self.afficheur_24)
        self.label_74.setObjectName(u"label_74")
        self.label_74.setGeometry(QRect(130, 40, 28, 16))
        self.lcdNumber_18 = QLCDNumber(self.afficheur_24)
        self.lcdNumber_18.setObjectName(u"lcdNumber_18")
        self.lcdNumber_18.setGeometry(QRect(0, 20, 121, 41))
        self.lcdNumber_18.setSmallDecimalPoint(False)
        self.afficheur_25 = QWidget(self.frame_7)
        self.afficheur_25.setObjectName(u"afficheur_25")
        self.afficheur_25.setGeometry(QRect(20, 150, 161, 61))
        self.label_75 = QLabel(self.afficheur_25)
        self.label_75.setObjectName(u"label_75")
        self.label_75.setGeometry(QRect(0, 0, 85, 16))
        self.label_76 = QLabel(self.afficheur_25)
        self.label_76.setObjectName(u"label_76")
        self.label_76.setGeometry(QRect(130, 40, 28, 16))
        self.lcdNumber_19 = QLCDNumber(self.afficheur_25)
        self.lcdNumber_19.setObjectName(u"lcdNumber_19")
        self.lcdNumber_19.setGeometry(QRect(0, 20, 121, 41))
        self.lcdNumber_19.setSmallDecimalPoint(False)
        self.label_80 = QLabel(self.Container_6)
        self.label_80.setObjectName(u"label_80")
        self.label_80.setGeometry(QRect(0, 0, 37, 16))
        self.Container_7 = QWidget(self.tab)
        self.Container_7.setObjectName(u"Container_7")
        self.Container_7.setGeometry(QRect(260, 20, 191, 181))
        self.frame_8 = QFrame(self.Container_7)
        self.frame_8.setObjectName(u"frame_8")
        self.frame_8.setGeometry(QRect(0, 20, 191, 161))
        self.frame_8.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_8.setFrameShadow(QFrame.Shadow.Raised)
        self.afficheur_22 = QWidget(self.frame_8)
        self.afficheur_22.setObjectName(u"afficheur_22")
        self.afficheur_22.setGeometry(QRect(20, 10, 161, 61))
        self.label_70 = QLabel(self.afficheur_22)
        self.label_70.setObjectName(u"label_70")
        self.label_70.setGeometry(QRect(0, 0, 71, 16))
        self.label_77 = QLabel(self.afficheur_22)
        self.label_77.setObjectName(u"label_77")
        self.label_77.setGeometry(QRect(130, 40, 15, 16))
        self.lcdNumber_20 = QLCDNumber(self.afficheur_22)
        self.lcdNumber_20.setObjectName(u"lcdNumber_20")
        self.lcdNumber_20.setGeometry(QRect(0, 20, 121, 41))
        self.lcdNumber_20.setSmallDecimalPoint(False)
        self.afficheur_26 = QWidget(self.frame_8)
        self.afficheur_26.setObjectName(u"afficheur_26")
        self.afficheur_26.setGeometry(QRect(20, 80, 161, 61))
        self.label_78 = QLabel(self.afficheur_26)
        self.label_78.setObjectName(u"label_78")
        self.label_78.setGeometry(QRect(0, 0, 71, 16))
        self.label_79 = QLabel(self.afficheur_26)
        self.label_79.setObjectName(u"label_79")
        self.label_79.setGeometry(QRect(130, 40, 28, 16))
        self.lcdNumber_21 = QLCDNumber(self.afficheur_26)
        self.lcdNumber_21.setObjectName(u"lcdNumber_21")
        self.lcdNumber_21.setGeometry(QRect(0, 20, 121, 41))
        self.lcdNumber_21.setSmallDecimalPoint(False)
        self.label_83 = QLabel(self.Container_7)
        self.label_83.setObjectName(u"label_83")
        self.label_83.setGeometry(QRect(0, 0, 37, 16))
        self.listWidget_testBench = QListWidget(self.tab)
        self.listWidget_testBench.setObjectName(u"listWidget_testBench")
        self.listWidget_testBench.setGeometry(QRect(30, 310, 1471, 461))
        self.listWidget_testBench.setAutoFillBackground(False)
        self.listWidget_testBench.setFrameShape(QFrame.Shape.Box)
        self.Container_11 = QWidget(self.tab)
        self.Container_11.setObjectName(u"Container_11")
        self.Container_11.setGeometry(QRect(490, 20, 191, 181))
        self.frame_13 = QFrame(self.Container_11)
        self.frame_13.setObjectName(u"frame_13")
        self.frame_13.setGeometry(QRect(0, 20, 191, 161))
        self.frame_13.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_13.setFrameShadow(QFrame.Shadow.Raised)
        self.afficheur_23 = QWidget(self.frame_13)
        self.afficheur_23.setObjectName(u"afficheur_23")
        self.afficheur_23.setGeometry(QRect(20, 10, 161, 61))
        self.label_71 = QLabel(self.afficheur_23)
        self.label_71.setObjectName(u"label_71")
        self.label_71.setGeometry(QRect(0, 0, 71, 16))
        self.label_81 = QLabel(self.afficheur_23)
        self.label_81.setObjectName(u"label_81")
        self.label_81.setGeometry(QRect(130, 40, 15, 16))
        self.lcdNumber_22 = QLCDNumber(self.afficheur_23)
        self.lcdNumber_22.setObjectName(u"lcdNumber_22")
        self.lcdNumber_22.setGeometry(QRect(0, 20, 121, 41))
        self.lcdNumber_22.setSmallDecimalPoint(False)
        self.afficheur_27 = QWidget(self.frame_13)
        self.afficheur_27.setObjectName(u"afficheur_27")
        self.afficheur_27.setGeometry(QRect(20, 80, 161, 61))
        self.label_82 = QLabel(self.afficheur_27)
        self.label_82.setObjectName(u"label_82")
        self.label_82.setGeometry(QRect(0, 0, 71, 16))
        self.label_84 = QLabel(self.afficheur_27)
        self.label_84.setObjectName(u"label_84")
        self.label_84.setGeometry(QRect(130, 40, 28, 16))
        self.lcdNumber_23 = QLCDNumber(self.afficheur_27)
        self.lcdNumber_23.setObjectName(u"lcdNumber_23")
        self.lcdNumber_23.setGeometry(QRect(0, 20, 121, 41))
        self.lcdNumber_23.setSmallDecimalPoint(False)
        self.label_85 = QLabel(self.Container_11)
        self.label_85.setObjectName(u"label_85")
        self.label_85.setGeometry(QRect(0, 0, 55, 16))
        self.Container_12 = QWidget(self.tab)
        self.Container_12.setObjectName(u"Container_12")
        self.Container_12.setGeometry(QRect(720, 20, 201, 111))
        self.frame_14 = QFrame(self.Container_12)
        self.frame_14.setObjectName(u"frame_14")
        self.frame_14.setGeometry(QRect(0, 20, 201, 91))
        self.frame_14.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_14.setFrameShadow(QFrame.Shadow.Raised)
        self.afficheur_28 = QWidget(self.frame_14)
        self.afficheur_28.setObjectName(u"afficheur_28")
        self.afficheur_28.setGeometry(QRect(20, 10, 161, 61))
        self.label_86 = QLabel(self.afficheur_28)
        self.label_86.setObjectName(u"label_86")
        self.label_86.setGeometry(QRect(0, 0, 71, 16))
        self.label_87 = QLabel(self.afficheur_28)
        self.label_87.setObjectName(u"label_87")
        self.label_87.setGeometry(QRect(130, 40, 32, 16))
        self.lcdNumber_24 = QLCDNumber(self.afficheur_28)
        self.lcdNumber_24.setObjectName(u"lcdNumber_24")
        self.lcdNumber_24.setGeometry(QRect(0, 20, 121, 41))
        self.lcdNumber_24.setSmallDecimalPoint(False)
        self.label_90 = QLabel(self.Container_12)
        self.label_90.setObjectName(u"label_90")
        self.label_90.setGeometry(QRect(0, 0, 55, 16))
        self.tabWidget.addTab(self.tab, "")
        self.Paramtres = QWidget()
        self.Paramtres.setObjectName(u"Paramtres")
        self.widget = QWidget(self.Paramtres)
        self.widget.setObjectName(u"widget")
        self.widget.setGeometry(QRect(20, 20, 621, 284))
        self.frame = QFrame(self.widget)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(0, 20, 621, 264))
        self.frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QFrame.Shadow.Raised)
        self.label_43 = QLabel(self.frame)
        self.label_43.setObjectName(u"label_43")
        self.label_43.setGeometry(QRect(10, 10, 99, 16))
        self.numInput_14 = QWidget(self.frame)
        self.numInput_14.setObjectName(u"numInput_14")
        self.numInput_14.setGeometry(QRect(10, 70, 149, 61))
        self.label_56 = QLabel(self.numInput_14)
        self.label_56.setObjectName(u"label_56")
        self.label_56.setGeometry(QRect(0, 0, 149, 16))
        self.spinBox_logFrequency = QSpinBox(self.numInput_14)
        self.spinBox_logFrequency.setObjectName(u"spinBox_logFrequency")
        self.spinBox_logFrequency.setGeometry(QRect(0, 20, 121, 41))
        self.spinBox_logFrequency.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.UpDownArrows)
        self.spinBox_logFrequency.setMinimum(1)
        self.spinBox_logFrequency.setValue(1)
        self.label_57 = QLabel(self.numInput_14)
        self.label_57.setObjectName(u"label_57")
        self.label_57.setGeometry(QRect(130, 40, 19, 16))
        self.numInput_13 = QWidget(self.frame)
        self.numInput_13.setObjectName(u"numInput_13")
        self.numInput_13.setGeometry(QRect(10, 140, 148, 61))
        self.label_52 = QLabel(self.numInput_13)
        self.label_52.setObjectName(u"label_52")
        self.label_52.setGeometry(QRect(0, 0, 139, 16))
        self.spinBox_fileSizeLimit = QSpinBox(self.numInput_13)
        self.spinBox_fileSizeLimit.setObjectName(u"spinBox_fileSizeLimit")
        self.spinBox_fileSizeLimit.setGeometry(QRect(0, 20, 121, 41))
        self.spinBox_fileSizeLimit.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.UpDownArrows)
        self.spinBox_fileSizeLimit.setMinimum(1)
        self.spinBox_fileSizeLimit.setValue(15)
        self.label_55 = QLabel(self.numInput_13)
        self.label_55.setObjectName(u"label_55")
        self.label_55.setGeometry(QRect(130, 40, 18, 16))
        self.label_44 = QLabel(self.frame)
        self.label_44.setObjectName(u"label_44")
        self.label_44.setGeometry(QRect(10, 210, 197, 16))
        self.pushButton_LogOnOff = QPushButton(self.frame)
        self.pushButton_LogOnOff.setObjectName(u"pushButton_LogOnOff")
        self.pushButton_LogOnOff.setGeometry(QRect(10, 230, 75, 24))
        self.pushButton_LogOnOff.setCheckable(True)
        self.pushButton_LogOnOff.setChecked(True)
        self.listWidget_logPath = QListWidget(self.frame)
        self.listWidget_logPath.setObjectName(u"listWidget_logPath")
        self.listWidget_logPath.setGeometry(QRect(10, 30, 591, 31))
        self.listWidget_logPath.setFrameShape(QFrame.Shape.Box)
        self.label = QLabel(self.widget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(0, 0, 161, 16))
        self.widget_2 = QWidget(self.Paramtres)
        self.widget_2.setObjectName(u"widget_2")
        self.widget_2.setGeometry(QRect(700, 20, 621, 284))
        self.frame_5 = QFrame(self.widget_2)
        self.frame_5.setObjectName(u"frame_5")
        self.frame_5.setGeometry(QRect(0, 20, 621, 264))
        self.frame_5.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QFrame.Shadow.Raised)
        self.label_51 = QLabel(self.frame_5)
        self.label_51.setObjectName(u"label_51")
        self.label_51.setGeometry(QRect(10, 10, 171, 16))
        self.pushButton_Refresh = QPushButton(self.frame_5)
        self.pushButton_Refresh.setObjectName(u"pushButton_Refresh")
        self.pushButton_Refresh.setGeometry(QRect(510, 30, 80, 24))
        self.pushButton_Refresh.setCheckable(False)
        self.pushButton_Refresh.setChecked(False)
        self.listWidget_PortList = QListWidget(self.frame_5)
        self.listWidget_PortList.setObjectName(u"listWidget_PortList")
        self.listWidget_PortList.setGeometry(QRect(10, 31, 481, 221))
        self.listWidget_PortList.setFrameShape(QFrame.Shape.Box)
        self.label_22 = QLabel(self.widget_2)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(0, 0, 161, 16))
        icon = QIcon(QIcon.fromTheme(u"applications-development"))
        self.tabWidget.addTab(self.Paramtres, icon, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.label_65.setText(QCoreApplication.translate("MainWindow", u"Vide primaire", None))
        self.label_72.setText(QCoreApplication.translate("MainWindow", u"mbar", None))
        self.label_73.setText(QCoreApplication.translate("MainWindow", u"Vide primaire", None))
        self.label_74.setText(QCoreApplication.translate("MainWindow", u"mbar", None))
        self.label_75.setText(QCoreApplication.translate("MainWindow", u"Vide secondaire", None))
        self.label_76.setText(QCoreApplication.translate("MainWindow", u"mbar", None))
        self.label_80.setText(QCoreApplication.translate("MainWindow", u"Pompe", None))
        self.label_70.setText(QCoreApplication.translate("MainWindow", u"Courant", None))
        self.label_77.setText(QCoreApplication.translate("MainWindow", u"\u00b5A", None))
        self.label_78.setText(QCoreApplication.translate("MainWindow", u"Tension", None))
        self.label_79.setText(QCoreApplication.translate("MainWindow", u"KV", None))
        self.label_83.setText(QCoreApplication.translate("MainWindow", u"Puller", None))
        self.label_71.setText(QCoreApplication.translate("MainWindow", u"Courant", None))
        self.label_81.setText(QCoreApplication.translate("MainWindow", u"\u00b5A", None))
        self.label_82.setText(QCoreApplication.translate("MainWindow", u"Tension", None))
        self.label_84.setText(QCoreApplication.translate("MainWindow", u"KV", None))
        self.label_85.setText(QCoreApplication.translate("MainWindow", u"Electrodes", None))
        self.label_86.setText(QCoreApplication.translate("MainWindow", u"D\u00e9bit", None))
        self.label_87.setText(QCoreApplication.translate("MainWindow", u"SCCM", None))
        self.label_90.setText(QCoreApplication.translate("MainWindow", u"Gaz", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"TestBench", None))
        self.label_43.setText(QCoreApplication.translate("MainWindow", u"Chemin du dossier", None))
        self.label_56.setText(QCoreApplication.translate("MainWindow", u"Fr\u00e9quence d'enregistrement", None))
        self.label_57.setText(QCoreApplication.translate("MainWindow", u"Sec", None))
        self.label_52.setText(QCoreApplication.translate("MainWindow", u"Limite de taille par fichiers", None))
        self.label_55.setText(QCoreApplication.translate("MainWindow", u"Mb", None))
        self.label_44.setText(QCoreApplication.translate("MainWindow", u"Activer l'enregistrement des donn\u00e9es", None))
        self.pushButton_LogOnOff.setText(QCoreApplication.translate("MainWindow", u"On", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Enregistrement des donn\u00e9es", None))
        self.label_51.setText(QCoreApplication.translate("MainWindow", u"Ports disponibles", None))
        self.pushButton_Refresh.setText(QCoreApplication.translate("MainWindow", u"Rafraichir", None))
        self.label_22.setText(QCoreApplication.translate("MainWindow", u"Appareils connect\u00e9s", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Paramtres), QCoreApplication.translate("MainWindow", u"Param\u00e8tres", None))
    # retranslateUi

